version: 2.1

orbs:
  jira: circleci/jira@2.1.0
  jq: circleci/jq@3.0.0

executors:
  java:
    docker:
      - image: cimg/openjdk:21.0

jobs:
  build_leaflet-rest-clients-pack:
    executor: java
    steps:
      - checkout
      - run:
          command: mvn clean deploy -s .circleci/settings.xml
          name: Build and upload to GitHub Packages repository
      - store_test_results:
          path: backend-rest-client/target/failsafe-reports
      - store_test_results:
          path: failover-rest-client/target/failsafe-reports
      - store_test_results:
          path: recaptcha-rest-client/target/failsafe-reports
      - store_test_results:
          path: tlp-rest-client/target/failsafe-reports
      - store_test_results:
          path: tms-rest-client/target/failsafe-reports
      - store_test_results:
          path: lens-rest-client/target/failsafe-reports
      - store_test_results:
          path: lsrs-rest-client/target/failsafe-reports

workflows:
  build:
    jobs:
      - build_leaflet-rest-clients-pack:
         context: leaflet_ci
         filters:
           branches:
             only:
               - master
         post-steps:
           - jira/notify:
               pipeline_id: << pipeline.id >>
               pipeline_number: << pipeline.number >>

  version: 2
